INSERT Clientes VALUES(1, 'Empresa 1', null, null, null, 'Dirección empresa 1', null, '555-0180', null)
INSERT Clientes VALUES(2, null, 'Emily', 'Jordan', 'Williams', 'Dirección persona 2', null, '555-0181', null)
INSERT Clientes VALUES(1, 'Empresa 3', null, null, null, 'Dirección empresa 3', null, '555-0182', null)
INSERT Clientes VALUES(1, 'Empresa 4', null, null, null, 'Dirección empresa 4', null, '555-0183', null)
INSERT Clientes VALUES(1, 'Empresa 5', null, null, null, 'Dirección empresa 5', null, '555-0184', null)
INSERT Clientes VALUES(1, 'Empresa 6', null, null, null, 'Dirección empresa 6', null, '555-0185', null)
INSERT Clientes VALUES(1, 'Empresa 7', null, null, null, 'Dirección empresa 7', null, '555-0186', null)
INSERT Clientes VALUES(1, 'Empresa 8', null, null, null, 'Dirección empresa 8', null, '555-0187', null)